name: typed_cache_json
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/saulogatti/typed_cache_json
publish_to: none
environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  # typed_cache:
  #   path: ../typed_cache
  typed_cache:
    git:
      url: https://github.com/saulogatti/typed_cache.git
      ref: main
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
