name: typed_cache_json
description: A typed cache implementation for Flutter that uses JSON serialization.
version: 0.2.1
repository: https://github.com/saulogatti/typed_cache_json

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5

  typed_cache: ^0.1.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
